### ISSUE TITLE
Admin Dashboard

### ISSUE THREAD

**Issue by joshelvn11** [joshelvn11/staysuite#4]
### User Story
As a **Customer** **I can** view the admin dashboard **so that I** I can access admin functionality

### Acceptance Criteria
- [ ] When accessing manage.staysuite.net as a logged in user I can see the admin page/dashboard
- [ ] When accessing the dashboard I can see a greeting message with my username
- [ ] When accessing the manage.staysuite.net as a logged out user I am redirected to the login page

### Tasks
- [ ] Create the basic admin dashboard framework (menu bar, page header, page content with sample data)
- [ ] Create a redirect to the login page when a user is logged out
